version: 2
updates:
    # NPM packages
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'type: chore'
    # Cargo
    - package-ecosystem: 'cargo'
      directory: '/src-tauri'
      schedule:
          interval: 'weekly'
      labels:
          - 'type: chore'
