# version: 2
# updates:
#     # NPM packages
#     - package-ecosystem: 'npm'
#       directory: '/'
#       schedule:
#           interval: 'monthly'
#       labels:
#           - chore
#     # Cargo
#     - package-ecosystem: 'cargo'
#       directory: '/src-tauri'
#       schedule:
#           interval: 'monthly'
#       labels:
#           - chore
