on:
    push:
        paths-ignore:
            - src-tauri/**

name: Style

jobs:
    check_style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Ignore tauri files
              id: changed-non-tauri-files
              uses: tj-actions/changed-files@v39
              with:
                  files_ignore: src-tauri/**

            - name: Setup node
              if: steps.changed-non-tauri-files.outputs.any_changed == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: 21

            - name: Install frontend dependencies
              if: steps.changed-non-tauri-files.outputs.any_changed == 'true'
              run: npm install

            - name: Cache node modules
              if: steps.changed-non-tauri-files.outputs.any_changed == 'true'
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node_modules-${{hashFiles('package.lock')}}
                  restore-keys: node_modules-

            - name: Prettier
              if: steps.changed-non-tauri-files.outputs.any_changed == 'true'
              run: npm run prettier:check

            - name: Stylelint
              if: steps.changed-non-tauri-files.outputs.any_changed == 'true'
              run: npm run stylelint:check
